from pydantic import BaseModel, Field, EmailStr
from typing import Optional, List
from datetime import datetime


# ─── Auth ─────────────────────────────────────────────────────────────────────

class LoginRequest(BaseModel):
    email: EmailStr
    password: str

class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"


# ─── Cases ────────────────────────────────────────────────────────────────────

class CaseCreate(BaseModel):
    title: str = Field(..., min_length=3, max_length=255)
    description: Optional[str] = None
    classification: str = "RESTRICTED"

class CaseUpdate(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    status: Optional[str] = None
    classification: Optional[str] = None

class CaseResponse(BaseModel):
    id: str
    case_number: str
    title: str
    description: Optional[str]
    classification: str
    status: str
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


# ─── Sources ──────────────────────────────────────────────────────────────────

class SourceCreate(BaseModel):
    platform: str = Field(..., min_length=1, max_length=50)
    handle: str = Field(..., min_length=1, max_length=255)
    source_url: Optional[str] = None
    import_method: str = "manual"

class SourceResponse(BaseModel):
    id: str
    platform: str
    handle: str
    token_count: int
    risk_level: str
    added_at: datetime

    class Config:
        from_attributes = True


# ─── Ingestion ────────────────────────────────────────────────────────────────

class IngestTextRequest(BaseModel):
    source_id: str
    text_content: str = Field(..., min_length=1)
    label: Optional[str] = None
    provenance_notes: Optional[str] = None


# ─── Stylometry ───────────────────────────────────────────────────────────────

class StyleCompareRequest(BaseModel):
    text_a: str = Field(..., min_length=10)
    text_b: str = Field(..., min_length=10)
    label_a: str = "Sample A"
    label_b: str = "Sample B"

class FeatureScores(BaseModel):
    lexical_density: float
    sentence_rhythm: float
    punctuation_pattern: float
    capitalisation_style: float
    informal_register: float
    function_word_dist: float
    vocabulary_overlap: float
    syntactic_patterns: float

class StyleCompareResponse(BaseModel):
    run_ref: str
    sample_a_label: str
    sample_b_label: str
    similarity_score: float
    confidence_low: float
    confidence_high: float
    verdict: str
    feature_scores: dict
    top_signals: List[str]
    token_count_a: int
    token_count_b: int
    created_at: str
    artifact_sha256: str
    disclaimer: str = (
        "This similarity score is an investigative lead only. "
        "It must not be used as definitive evidence of shared authorship "
        "without independent corroboration."
    )


# ─── Graph ────────────────────────────────────────────────────────────────────

class GraphResponse(BaseModel):
    nodes: list
    edges: list


# ─── Audit ────────────────────────────────────────────────────────────────────

class AuditEventResponse(BaseModel):
    id: str
    event_type: str
    actor: Optional[str]
    object_type: Optional[str]
    object_id: Optional[str]
    sha256: Optional[str]
    timestamp_utc: datetime
    metadata_json: dict
    analyst_note: Optional[str]

    class Config:
        from_attributes = True


# ─── Reports ──────────────────────────────────────────────────────────────────

class ReportCreateRequest(BaseModel):
    include_stylometry: bool = True
    include_graph: bool = True
    include_audit_trail: bool = True
    analyst_note: Optional[str] = None
    format: str = "json"  # "json" | "pdf"

class ReportResponse(BaseModel):
    report_id: str
    case_id: str
    case_number: str
    generated_at: str
    artifact_sha256: str
    sections: dict
    disclaimer: str = (
        "This report was generated by Vanguard OSINT for lawful investigative purposes. "
        "All similarity scores are investigative leads and must be corroborated independently."
    )
